import {
  itemsPlusFee,
  negativeCoefficient,
  twoStep,
} from "@/content/algebra1/linear-equations/s1-templates";
import { defineChapter } from "@/content/chapter";
import { defineWorkedExample } from "@/content/lesson";
import type { ChapterVideo } from "@/content/types";

// The textbook chapter for solving two-step linear equations (AI-A.REI.3). Written for a grade 6
// to 10 reader: short sentences, everyday words; tests/unit/content/chapter.test.ts caps sentence
// length. Every worked example is cut from one of the session's own templates, pinned to the
// numbers its reasons were written for and generated by the engine, so its steps can never
// disagree with the text beside them.

/** The example the whole chapter and the coach's prompt refer back to: always 3x + 5 = 20. */
export const TWO_STEP_EXAMPLE = defineWorkedExample({
  template: twoStep,
  values: { a: 3, b: 5, x: 5 },
  reasons: [
    "The 5 is added to 3x. Subtracting 5 undoes the adding, and doing it to both sides keeps them equal.",
    "3x means 3 times x. Dividing both sides by 3 undoes the multiplying and leaves x by itself.",
  ],
  check: {
    equation: "3(5) + 5 = 20",
    reason: "3 times 5 is 15, and 15 + 5 is 20. Both sides match, so x = 5 is right.",
  },
});

const negativeExample = defineWorkedExample({
  template: negativeCoefficient,
  values: { a: -4, b: -9, x: -5 },
  reasons: [
    "The 9 is subtracted from -4x. Adding 9 undoes the subtracting. On the right, 11 + 9 is 20.",
    "-4x means -4 times x, so divide both sides by -4. 20 divided by -4 is -5: a positive divided by a negative is negative.",
  ],
  check: {
    equation: "-4(-5) - 9 = 11",
    reason: "-4 times -5 is 20, and 20 - 9 is 11. Both sides match, so x = -5 is right.",
  },
});

/** The session's items-plus-fee story with its numbers fixed: 3 notebooks and $4 of pens for $31. */
const wordExample = defineWorkedExample({
  template: itemsPlusFee,
  values: { a: 3, b: 4, x: 9 },
  reasons: [
    "The $4 pack of pens is a one-time cost added on. Subtracting 4 from both sides takes it out: 31 - 4 is 27.",
    "3x is the cost of 3 notebooks. Dividing both sides by 3 gives the cost of one: 27 divided by 3 is 9.",
  ],
  check: {
    equation: "3(9) + 4 = 31",
    reason:
      "3 notebooks at $9 is $27, plus $4 for the pens is $31. That matches, so one notebook costs $9.",
  },
});

// Fetched on the day recorded, through YouTube's oEmbed endpoint: each answered 200 with this
// title and channel. docs/content-review.md lists the same three.
const VIDEOS = {
  mathAntics: {
    title: "Algebra Basics: Solving 2-Step Equations",
    source: "Math Antics",
    url: "https://www.youtube.com/watch?v=LDIiYKYvvdA",
    verified: "2026-10-02",
  },
  khanSolving: {
    title: "Solving two-step equations",
    source: "Khan Academy",
    url: "https://www.youtube.com/watch?v=_y_Q3_B2Vh8",
    verified: "2026-10-02",
  },
  khanExample: {
    title: "Example: two-step equations",
    source: "Khan Academy",
    url: "https://www.youtube.com/watch?v=tuVd355R-OQ",
    verified: "2026-10-02",
  },
} as const satisfies Record<string, ChapterVideo>;

export const twoStepChapter = defineChapter({
  title: "Solving two-step linear equations",
  sections: [
    {
      id: "what-it-is",
      heading: "What a two-step equation is",
      paragraphs: [
        "An equation says that two amounts are equal. The letter x stands for a number we do not know yet.",
        "In a two-step equation, two things happen to x. First, x is multiplied by a number. Then a number is added or subtracted.",
        "Look at 3x + 5 = 20. Here x is multiplied by 3, and then 5 is added. The result is 20.",
        "Linear means x stands on its own, times a number. It is never squared and never under a root.",
        "Solving the equation means finding the number x stands for. Here x is 5, because 3 times 5 is 15, and 15 plus 5 is 20.",
      ],
    },
    {
      id: "balance",
      heading: "The balance idea",
      paragraphs: [
        "Picture the equation as a balance scale. The left pan holds 3x + 5. The right pan holds 20. The scale is level, because the two sides are equal.",
        "Take 5 off the left pan only, and the scale tips. Take 5 off both pans, and it stays level. That is the one rule of solving: whatever you do to one side, do to the other side too.",
        "You can add the same number to both sides. You can subtract it, multiply by it, or divide by it. The equation stays true every time. The only move that is never allowed is dividing by zero.",
      ],
      diagram: { kind: "balance", a: 3, b: 5, c: 20 },
      video: VIDEOS.mathAntics,
    },
    {
      id: "undo-moves",
      heading: "The two undo moves, in order",
      paragraphs: [
        "To get x by itself, undo the two things that happened to it. Undo them in reverse order. You put on socks and then shoes, so the shoes come off first.",
        "Move 1 undoes the adding or subtracting. If a number is added to the x term, subtract it from both sides. If a number is subtracted, add it to both sides.",
        "Move 2 undoes the multiplying. Divide both sides by the number in front of x. That number is called the coefficient.",
        "Why this order? In 3x + 5, the 5 was added after the multiplying, so it is the outer layer. Dividing first is allowed, but it turns the 5 into a fraction and makes more work.",
      ],
      diagram: { kind: "undo-ladder", a: 3, b: 5, x: 5 },
      video: VIDEOS.khanSolving,
    },
    {
      id: "example-positive",
      heading: "Worked example 1: a positive coefficient",
      paragraphs: [
        "Solve 3x + 5 = 20. Read the equation first: x is multiplied by 3, then 5 is added. Reveal each step and read why it works before you move on.",
      ],
      example: TWO_STEP_EXAMPLE,
    },
    {
      id: "example-negative",
      heading: "Worked example 2: a negative coefficient",
      paragraphs: [
        "A negative coefficient works the same way. Keep the minus sign with its number, and the two moves do not change.",
        "Solve -4x - 9 = 11. The 9 is subtracted, so add 9 to both sides. Then divide both sides by -4, minus sign and all.",
        "Watch the signs on the integer steps. Adding 9 to 11 lands on 20, and 20 divided by -4 is -5. A positive divided by a negative is always negative.",
      ],
      diagram: { kind: "number-line", from: 11, step: 9 },
      example: negativeExample,
    },
    {
      id: "example-word",
      heading: "Worked example 3: a word problem",
      paragraphs: [
        "A word problem hides a two-step equation in a story. Find the repeated part, the one-time part, and the total.",
        "In the story below, the notebooks are the repeated part: 3 of them, the same price each. The pack of pens is the one-time part. What you paid is the total.",
        "Let x be the price of one notebook in dollars. Then 3 notebooks cost 3x, the pens add 4, and the total is 31. That gives 3x + 4 = 31.",
        "Solve it with the same two moves. At the end, say what x means: one notebook costs $9.",
      ],
      example: wordExample,
      video: VIDEOS.khanExample,
    },
    {
      id: "mistakes",
      heading: "Common mistakes",
      paragraphs: [
        "These five slips cost the most points. Each one has a quick fix. Read the wrong line, then the fix.",
      ],
      mistakes: [
        {
          wrong: "3x + 5 = 20, so 3x = 25",
          fix: "The 5 is added, so subtract it. 20 - 5 is 15, not 25. Ask yourself what undoes adding 5.",
        },
        {
          wrong: "3x + 5 = 20, so 3x = 20",
          fix: "The 5 came off the left side only, so the scale tipped. Both sides lose 5: 3x = 15.",
        },
        {
          wrong: "3x = 15, so x = 15 - 3 = 12",
          fix: "3x means 3 times x. Undo multiplying by dividing, not subtracting. 15 divided by 3 is 5.",
        },
        {
          wrong: "3x + 5 = 20, so x + 5 = 20 ÷ 3",
          fix: "If you divide, you must divide every term on both sides. It is easier to subtract 5 first and then divide 3x = 15 by 3.",
        },
        {
          wrong: "-4x = 20, so x = 5",
          fix: "The coefficient is -4, not 4. 20 divided by -4 is -5. Check it: -4 times -5 is 20.",
        },
      ],
    },
    {
      id: "check",
      heading: "Check your answer",
      paragraphs: [
        "A check takes ten seconds and catches most slips. Put your answer back in for x in the original equation, not in a later line.",
        "Take 3x + 5 = 20 with x = 5. Then 3 times 5 is 15, and 15 plus 5 is 20. Both sides match, so x = 5 is right.",
        "If the two sides do not match, the answer is wrong. Go back to the first step and look at the sign and the order of the moves.",
        "In a word problem, also ask whether the answer makes sense. A notebook that costs $400, or -$9, means something went wrong.",
      ],
    },
    {
      id: "key-learnings",
      heading: "Key learnings",
      paragraphs: ["Seven lines to remember. They come back beside every practice problem."],
      points: [
        "A two-step equation does two things to x: multiplies it, then adds or subtracts a number.",
        "Whatever you do to one side, do to the other side.",
        "Undo in reverse order: first the adding or subtracting, then the multiplying.",
        "Undo adding by subtracting, undo subtracting by adding, undo multiplying by dividing.",
        "Keep the minus sign with its number: a negative coefficient divides with its sign.",
        "Check by putting your answer back into the original equation.",
        "In a word problem, say what x stands for before you solve and after.",
      ],
    },
    {
      id: "next",
      heading: "What comes next",
      paragraphs: [
        "Upcoming: equations with x on both sides, like 5x + 2 = 3x + 10. You will add one move, getting both x terms onto one side first.",
        "After that come equations with parentheses, like 2(x + 3) = 14. Everything in this chapter still applies. The balance rule never changes.",
      ],
    },
  ],
});
